from enum import Enum

class Stage(str, Enum):
    DISCOVERED="DISCOVERED"; FETCHED="FETCHED"; HASHED="HASHED"; TRIAGED="TRIAGED"
    EXTRACTED="EXTRACTED"; NORMALIZED="NORMALIZED"; AUTO_QA="AUTO_QA"
    SILVER="SILVER"; PANEL_LINKED="PANEL_LINKED"; ANALYTIC="ANALYTIC"
    FETCH_RETRY="FETCH_RETRY"; SOURCE_REDISCOVERY="SOURCE_REDISCOVERY"
    VISION_REQUIRED="VISION_REQUIRED"; CONFLICT="CONFLICT"; DEAD_LETTER="DEAD_LETTER"

HAPPY_PATH=[Stage.DISCOVERED,Stage.FETCHED,Stage.HASHED,Stage.TRIAGED,Stage.EXTRACTED,
            Stage.NORMALIZED,Stage.AUTO_QA,Stage.SILVER,Stage.PANEL_LINKED,Stage.ANALYTIC]
